export const CAPACITY_NORMAL_HOURS = 40
export const CAPACITY_EXTRA_HOURS = 8

export const NB_HOURS_FOR_VACATION = 8
export const HOURS_REGULAR_DAY = 8

export const REASONS_ABSENCE = {
  WE: "WE",
  VACATION: "VACATION",
  UNPAID_VACATION: "UNPAID_VACATION",
  RTT: "RTT",
  PUBLIC_HOLIDAY: "PUBLIC_HOLIDAY",
  SICKNESS: "SICKNESS",
  MATERNITY: "MATERNITY",
  OTHER: "OTHER",
}
